# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Qwen2 14B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download Qwen/Qwen2.5-14B-Instruct --output-dir /tmp/Qwen2.5-14B-Instruct --ignore-patterns None
#
# To launch on 4 devices, run the following command from root:
#   tune run --nnodes 1 --nproc_per_node 4 full_finetune_distributed --config qwen2/14B_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nnodes 1 --nproc_per_node 4 full_finetune_distributed --config qwen2/14B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# Single device full finetuning requires more memory optimizations. It's
# best to use 14B_full.yaml for those cases

# Tokenizer
tokenizer:
  _component_: torchtune.models.qwen2.qwen2_tokenizer
  path: /home/ubuntu/workspace/Qwen2.5-14B-Instruct/vocab.json
  merges_file: /home/ubuntu/workspace/Qwen2.5-14B-Instruct/merges.txt
  max_seq_len: null

# Dataset
dataset:
  _component_: torchtune.datasets.chat_dataset
  source: /home/ubuntu/workspace/dataset
  conversation_style: openai
  conversation_column: messages
  split: train
  train_on_input: False
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.qwen2.qwen25_14b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /home/ubuntu/workspace/Qwen2.5-14B-Instruct
  checkpoint_files: [
    model-00001-of-00008.safetensors,
    model-00002-of-00008.safetensors,
    model-00003-of-00008.safetensors,
    model-00004-of-00008.safetensors,
    model-00005-of-00008.safetensors,
    model-00006-of-00008.safetensors,
    model-00007-of-00008.safetensors,
    model-00008-of-00008.safetensors
  ]
  recipe_checkpoint: null
  output_dir: /tmp/Qwen2.5-14B-Instruct-ft
  model_type: QWEN2
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 12
epochs: 20
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  lr: 5e-6
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 1


# Training env
device: cuda

# Memory management
enable_activation_checkpointing: False

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  log_dir: torchtune
output_dir: /tmp/Qwen2.5-14B-Instruct-ft
log_every_n_steps: 1
log_peak_memory_stats: True
